/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AsideMenu: typeof import('./src/components/AsideMenu.vue')['default']
    BadgeComments: typeof import('./src/components/Badge/BadgeComments.vue')['default']
    BadgeGoods: typeof import('./src/components/Badge/BadgeGoods.vue')['default']
    BadgeStores: typeof import('./src/components/Badge/BadgeStores.vue')['default']
    Bilibili: typeof import('./src/components/Picture/Bilibili.vue')['default']
    Brief: typeof import('./src/components/Brief.vue')['default']
    CardReply: typeof import('./src/components/Message/CardReply.vue')['default']
    CheckBox: typeof import('./src/components/CheckBox.vue')['default']
    Comment: typeof import('./src/components/Comment.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    FooterGoods: typeof import('./src/components/Footer/FooterGoods.vue')['default']
    FooterReply: typeof import('./src/components/Footer/FooterReply.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HistoryBilibili: typeof import('./src/components/History/HistoryBilibili.vue')['default']
    IEpArrowLeft: typeof import('~icons/ep/arrow-left')['default']
    IEpArrowRight: typeof import('~icons/ep/arrow-right')['default']
    IEpCheck: typeof import('~icons/ep/check')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    PasswordInput: typeof import('./src/components/PasswordInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondComment: typeof import('./src/components/SecondComment.vue')['default']
    SelectInput: typeof import('./src/components/SelectInput.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    ToolButton: typeof import('./src/components/ToolButton.vue')['default']
    ToolIcon: typeof import('./src/components/ToolIcon.vue')['default']
    UnLogin: typeof import('./src/components/UnLogin.vue')['default']
  }
}
